### ISSUE TITLE
Feature Request: Turn OFF WiFi&Cell Data in iOS App Preferences

### ISSUE THREAD

**Issue by electocoded** [Flairmesh/FlooPaste#4]
The FMA100 USB device and app are very useful for bridging data over bluetooth between a fully-connected iOS device and a semi-isolated Linux/Windows computer. In that context security is critical. Unlike Android, iOS doesn't allow WiFi data to be turned-off on a per application basis at the OS layer (that feature is only available on iPhones sold in China: [screenshot](https://ibb.co/W0VZr13)). So it'd be great if you added the option to turn off all internet connectivity in the app preference pane similar to example linked above. The feature would add assurance that the data being bridged over Bluetooth is staying local only and not leaking to 3rd party servers.

**Comment by Flairmesh** [comment]
The iOS app "FlooPaste" doesn't have a setting to turn off Wifi access only because it won't/cannot access the networks for privacy concerns. iOS doesn't bother to show such an option to switch on/off a feature that doesn't exist for the App. So it's guaranteed that data being shared via the App is staying local only and not leaking to 3rd party servers.

**Comment by electocoded** [comment]
Thank you for correcting my misunderstanding on this. I've tested more carefully with a few apps and see that the setting options grow as apps ask for more permissions. This feature request was a mistake! Appreciate it.
